# Generated by Django 5.2.6 on 2025-09-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
