# Generated by Django 5.2.3 on 2025-09-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_trendingitem_options_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Order Placed'), ('Processing', 'Order Dispatched'), ('Shipped', 'Order in Transit'), ('Delivered', 'Delivered Successfully'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
